### ISSUE TITLE
[dados] incluir update_metadata nas demais pipelines

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#445]
- [x] br_bcb_agencia
- [x] br_bcb_estban
- [x] br_ons_avaliacao_operacao *
- [x] br_ons_estimativa_custos *
- [x] br_me_comex
- [x] br_anatel_banda_larga_fixa
- [x] br_anatel_telefonia_movel
- [x] br_b3_cotacoes *
- [x] br_anp_preco_combustiveis
- [x] br_rj_isp_seguranca_publica

**Comment by arthurfg** [comment]
### `br_bcb_agencia` @folhesgabriel 

#### Modelo antigo:
```py
        with case(update_metadata, True):
            update = update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                api_mode="prod",
                billing_project_id="basedosdados",
                date_format="yy-mm",
                is_bd_pro=True,
                is_free=True,
                time_delta=6,
                time_unit="months",
                upstream_tasks=[wait_for_materialization],
            )
```

#### Modelo novo:
```py
        with case(update_metadata, True):
            update = update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                api_mode="prod",
                billing_project_id="basedosdados",
                date_format="yy-mm",
                is_bd_pro=True,
                is_free=True,
                time_delta=6,
                time_unit="months",
                upstream_tasks=[wait_for_materialization],
            )
```

#### TODO:

- [ ] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [ ] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [ ] Caso precise, incluir `time_delta` e `time_unit`.
- [ ] Subir para o PR.
- [ ] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.

**Comment by arthurfg** [comment]
### `br_bcb_estban` @folhesgabriel 

#### Modelo antigo:
(já estava atualizado)
```py
        with case(update_metadata, True):
            update = update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                api_mode="prod",
                billing_project_id="basedosdados",
                date_format="yy-mm",
                is_bd_pro=True,
                is_free=True,
                time_delta=6,
                time_unit="months",
                upstream_tasks=[wait_for_materialization],
            )
```

#### Modelo novo:
```py
        with case(update_metadata, True):
            update = update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                api_mode="prod",
                billing_project_id="basedosdados",
                date_format="yy-mm",
                is_bd_pro=True,
                is_free=True,
                time_delta=6,
                time_unit="months",
                upstream_tasks=[wait_for_materialization],
            )
```

#### TODO:

- [x] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [x] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [x] Caso precise, incluir `time_delta` e `time_unit`.
- [x] Caso precise, criar novo coverage.
- [ ] Subir para o PR.
- [ ] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.

**Comment by arthurfg** [comment]
### `br_ons_avaliacao_operacao` @folhesgabriel 

#### Modelo antigo:

```py
        with case(update_metadata, True):
            update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                billing_project_id="basedosdados",            
                api_mode="prod",
                date_format="yy-mm-dd",
                upstream_tasks=[wait_for_materialization],
            )
```

#### Modelo novo:
```py
        with case(update_metadata, True):
            update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                billing_project_id="basedosdados",
                is_bd_pro = True,
                is_free = False,                
                api_mode="prod",
                date_format="yy-mm-dd",
                upstream_tasks=[wait_for_materialization],
            )
```

#### TODO:

- [x] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [x] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [x] Caso precise, incluir `time_delta` e `time_unit`.
- [x] Caso precise, criar novo coverage.
- [x] Subir para o PR.
- [ ] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.

**Comment by arthurfg** [comment]
### `br_me_comex_stat` @folhesgabriel 

#### Modelo antigo:

```py
        with case(update_metadata, True):
            update_django_metadata(
                dataset_id,
                table_id + "_atualizado",
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                api_mode="prod",
                billing_project_id="basedosdados",
                date_format="yy-mm",
                upstream_tasks=[update]
)
```

#### Modelo novo:
```py
        with case(update_metadata, True):
            update = update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                is_bd_pro=True,
                is_free=True,
                api_mode="prod",
                billing_project_id="basedosdados",
                date_format="yy-mm",
                time_delta=1,
                time_unit="months",
     
            )
```

#### TODO:

- [x] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [x] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [x] Caso precise, incluir `time_delta` e `time_unit`.
- [x] Caso precise, criar novo coverage.
- [x] Subir para o PR.
- [ ] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.

**Comment by arthurfg** [comment]
### `be_anatel_banda_larga_fixa` @tricktx  

#### Modelo antigo:

```py
        with case(update_metadata, True):
            date = get_today_date_atualizado()  # task que retorna a data atual
            update_django_metadata(
                dataset_id,
                table_id[2],
                metadata_type="DateTimeRange",
                bq_last_update=False,
                api_mode="prod",
                date_format="yy-mm",
                _last_date=date,
            )
```

#### Modelo novo:
```py
        with case(update_metadata, True):
            date = get_today_date_atualizado()  # task que retorna a data atual
            update_django_metadata(
                dataset_id,
                table_id[3],
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=False,
                is_bd_pro=True,
                is_free=True,
                time_delta=2,
                time_unit="months",                
                api_mode="prod",
                date_format="yy-mm",
                _last_date=date,
            )
```

#### TODO:

- [x] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [x] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [x] Caso precise, incluir `time_delta` e `time_unit`.
- [x] Caso precise, criar novo coverage.
- [x] Subir para o PR.
- [x] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.

**Comment by arthurfg** [comment]
### `br_anatel_telefonia_movel` @tricktx  

#### Modelo antigo:

```py
        with case(update_metadata, True):
            date = get_today_date_atualizado()  # task que retorna a data atual
            update_django_metadata(
                dataset_id,
                table_id[2],
                metadata_type="DateTimeRange",
                bq_last_update=False,
                api_mode="prod",
                date_format="yy-mm",
                _last_date=date,
            )
```

#### Modelo novo:
```py
        with case(update_metadata, True):
            date = get_today_date_atualizado()  # task que retorna a data atual
            update_django_metadata(
                dataset_id,
                table_id[3],
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=False,
                is_bd_pro=True,
                is_free=True,
                time_delta=2,
                time_unit="months",                
                api_mode="prod",
                date_format="yy-mm",
                _last_date=date,
            )
```

#### TODO:

- [x] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [x] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [x] Caso precise, incluir `time_delta` e `time_unit`.
- [x] Caso precise, criar novo coverage.
- [x] Subir para o PR.
- [ ] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.

**Comment by arthurfg** [comment]
### `br_br_cotacoes` @tricktx  

#### Modelo antigo:

```py
        with case(update_metadata, True):
            update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,      
                api_mode="prod",
                date_format="yy-mm-dd",
                _last_date=data_max,
                upstream_tasks=[wait_for_materialization],
```

#### Modelo novo:
```py
        with case(update_metadata, True):  # task que retorna a data atual
            update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=False,
                is_bd_pro=True,
                is_free=False,                
                api_mode="prod",
                date_format="yy-mm-dd",
                _last_date=data_max,
                upstream_tasks=[wait_for_materialization],
            )
```

#### TODO:

- [x] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [x] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [x] Caso precise, incluir `time_delta` e `time_unit`.
- [x] Caso precise, criar novo coverage.
- [x] Subir para o PR.
- [ ] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.

**Comment by arthurfg** [comment]
### `br_anp_precos_combustiveis` @tricktx  

#### Modelo antigo:

```py
        with case(update_metadata, True):
            update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                api_mode="prod",
                date_format="yy-mm-dd",
                _last_date=get_date_max_pro,
                upstream_tasks=[wait_upload_table],
            )
```

#### Modelo novo:
```py
        with case(update_metadata, True):
            update_django_metadata(
                dataset_id,
                table_id,
                metadata_type="DateTimeRange",
                bq_last_update=False,
                bq_table_last_year_month=True,
                api_mode="prod",
                date_format="yy-mm-dd",
                is_bd_pro=True,
                is_free=True,
                time_delta=6,
                time_unit="weeks",
                _last_date=get_date_max_pro,
                upstream_tasks=[wait_upload_table],
            )
```

#### TODO:

- [x] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [x] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [x] Caso precise, incluir `time_delta` e `time_unit`.
- [x] Caso precise, criar novo coverage.
- [x] Subir para o PR.
- [ ] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.

**Comment by arthurfg** [comment]
### `br_rj_isp_estatisticas_seguranca` @tricktx  

#### Modelo antigo:

```py
    with case(update_metadata, True):
        date = get_today_date()  # task que retorna a data atual
        update_django_metadata(
            dataset_id,
            table_id,
            metadata_type="DateTimeRange",
            bq_last_update=False,
            api_mode="prod",
            date_format="yy-mm",
            _last_date=date,
        )
```

#### Modelo novo:
```py
    with case(update_metadata, True):
        date = get_today_date()  # task que retorna a data atual
        update_django_metadata(
            dataset_id,
            table_id,
            metadata_type="DateTimeRange",
            bq_table_last_year_month=False,
            bq_last_update=False,
            is_bd_pro=False,
            is_free=True,                
            api_mode="prod",
            date_format="yy-mm",
            _last_date=date,
        )
```

#### TODO:

- [x] Alterar o caminho para `from pipelines.utils.metadata.tasks import update_django_metadata`.
- [x] Incluir os parâmetros `is_bd_pro` / `is_free`.
- [x] Caso precise, incluir `time_delta` e `time_unit`.
- [x] Caso precise, criar novo coverage.
- [x] Subir para o PR.
- [ ] Testar na cloud.
- [ ] Validar com o/a criador/a da pipeline.
- [ ] Fechar.
